### ISSUE TITLE
Aggiungere DockerFile

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-client#10]
# Aggiungere Dockerfile

- [x] Aggiungere il Dockerfile
- [x] Aggiornare il file README.md

## Aggiungere il Dockerfile

Nel Dockerfile devono essere descritti i passaggi per effettuare il deploy del client. Non dovrebbe essere necessario eseguire altri comandi oltre al `npm install`.

## Aggiornare il file README

Nel README.md bisogna elencare i comandi necessari per effettuare una corretta build e run del container. Non scrivere comandi a caso, ma correttamente strutturati come negli altri progetti.

**Comment by silviazandoli** [comment]
già completata
