### ISSUE TITLE
Creazione About Page

### ISSUE THREAD

**Issue by igor-lirussi** [Weather-Vortex/weather-vortex-client#2]

**Comment by Daniele-Tentoni** [comment]
Secondo di informazioni da inserire nell'about page ci sono:

1. Informazioni riguardanti il progetto, come il link all'organizzazione di Github, una piccola presentazione dello stesso, cosa dovrebbe fare, le funzionalità... Insomma, come fosse la piccola introduzione della relazione
2. Informazioni del server, come il link al repository, il link delle api, una breve descrizione di cosa ci si può trovare.
3. Informazioni del client, come il link al repository.
