### ISSUE TITLE
Pulsanti visualizza password tabbabili

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-client#26]
## Comportamento atteso

Mentre sto digitando la password o la conferma della password, posso premere il pulsante Tab per passare a digitare il campo successivo, rispettivamente la conferma della password o la spunta.

## Comportamento riscontrato

Premendo il tasto Tab, viene selezionato invece rispettivamente il pulsante di visualizza password e di visualizza di conferma della password.

## Discussione

Secondo questo è un comportamento controintuitivo. Da un campo mi aspetto di essere portato al successivo, come dovrebbe essere lato mobile.

❗ Lato mobile non è ancora stato provato questo comportamento, bisogna fare un'indagine il prima possibile.

**Comment by silviazandoli** [comment]
@Daniele-Tentoni a me fa così: sono nel campo password, premo tab e va al pulsante di visualizza password. poi premo tab di nuovo e va al campo di ridigitazione password. premo tab e va al pulsante di visualizza della password. Poi premo ancora tab e va nel campo successivo, ovvero quello del check di termini e condizioni. Nei campi successivi ci va solo che passa anche per i pulsanti di visualizza password. Ho provato lato mobile con lo strumento per sviluppatori e il comportamento è analogo. Provo a vedere se trovo qualcosa su internet
