### ISSUE TITLE
Le cards non vengono posizionate e dimensionate correttamente

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-client#45]
Sul mio smartphone le cards non hanno lo stesso margine a sinistra che a destra e la card di *Act* non viene nemmeno dimensionata correttamente, che dovrebbe essere larga come tutta la pagina.
![photo_2021-08-24_10-26-46](https://user-images.githubusercontent.com/11157241/130583596-82d3b409-d9a9-4ec1-92ea-fbb775442d87.jpg)

**Comment by silviazandoli** [comment]
già completata
