### ISSUE TITLE
VUE_APP_SERVER_URL valore errato

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-client#63]
# VUE_APP_SERVER_URL valore errato

Nella giornata di Martedì 31 Agosto è stata rilevata questa anomalia su Github Pages, nella pagina [Registrazioni](https://weather-vortex.github.io/weather-vortex-client/#/user/register): quando si premeva sul pulsante **Register** non veniva chiamato l'indirizzo del server giusto, che restituiva quindi un errore 404:
![image](https://user-images.githubusercontent.com/11157241/131810647-a1a4d017-2cd2-4ff2-bd9f-3bab5ebbae33.png)

## Indagine

Sui log del server compariva subito chiaro che la risorsa richiesta fosse `//api/register`, quindi non abbiamo indagato oltre.

## Soluzione

Modificare il valore della variabile d'ambiente `VUE_APP_SERVER_URL` all'indirizzo del server senza la `/` finale. 

In questo modo tutte le future chiamate al server dovranno come iniziale sempre `/` e poi la risorsa richiesta. In questo caso: `{server}/api/register`.

Si propone come unica modifica quindi di permettere che il deploy del client possa avvenire anche manualmente per *triggherare* questi aggiornamenti di variabili.

## Altro

Questa issue servirà anche ai posteri per risolvere casi simili. In quel caso riferirsi a questa issue.

**Comment by silviazandoli** [comment]
già completata
