### ISSUE TITLE
Aggiungere Aggregazione Previsioni Meteo

### ISSUE THREAD

**Issue by igor-lirussi** [Weather-Vortex/weather-vortex-client#72]
Le previsioni meteo vanno aggregate mano a mano che arrivano al client.
Allo scatenarsi dell'evento `this.socket.on("result", (result) => { ` , scaturito ad ogni risultato ricevuto dal server, la card che contiene l'aggregazione dei risultato va aggiornata. 

### Come aggiornare
1. Salvare una lista di condizioni meteo (cloud, sunny, .. ) e mostrare quella più frequente
2. Per il resto, fare la media, salvandosi un contatore di previsioni ottenute e la somma dei valori, per poi dividere.

**Comment by Daniele-Tentoni** [comment]
Aggiunta.
