### ISSUE TITLE
Pulire cookie se login fallisce

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-client#77]
Come avrete sicuramente riscontrato, nel caso in cui ci logghiamo con un utente e successivamente puliamo il database, rimane in memoria un cookie `auth` sporco, che non trova nessun riscontro nel database. Se poi proviamo ad aprire l'app, giustamente prova ad effettuare il login che fallisce e ritorna i soliti messaggi di errore. Bisogna fare in modo che se il token è scaduto (la chiamata a loggedIn fallisce) bisogna cancellare il token scaduto dalla memoria e non mostrare alcun messaggio di errore secondo me, così da forzare l'utente a tentare un nuovo login.

**Comment by Daniele-Tentoni** [comment]
Scrivete cosa ne pensate nei commenti, se siamo tutti d'accordo, rimuoviamo la label help wanted così ci possiamo lavorare su.

**Comment by silviazandoli** [comment]
Sono d'accordo, se capita all'esame non è tanto bello, e bisogna andare a cancellare il cookie sul browser per fare in modo che ritorni tutto normale

**Comment by silviazandoli** [comment]
bisogna aggiungere expiresIn nel token

**Comment by silviazandoli** [comment]
https://riptutorial.com/jwt/example/21537/remove-the-token-from-client-storage

**Comment by Daniele-Tentoni** [comment]
Non più necessario.
