### ISSUE TITLE
Indagare problemi interfaccia mobile pagina Previsioni

### ISSUE THREAD

**Issue by Daniele-Tentoni** [Weather-Vortex/weather-vortex-client#86]
Abbiamo rilevato problemi nell'uso da dispositivo mobile della pagina della forecasts. Principalmente i problemi sono due:
- [ ] 1. Abbiamo richiesto le previsioni per la città di Cesena. Da desktop ci mostra 3 cards dentro allo slider. Da mobile, lo slider è troppo stretto rispetto alla larghezza dello schermo, sia a destra che a sinistra. Le cards sarebbe meglio che siano centrate rispetto allo slider e che le frecce non occupino tutto quello spazio
![photo_2021-09-14_12-02-52](https://user-images.githubusercontent.com/11157241/133238041-2fea2285-8e75-4809-832a-05120def3f3d.jpg)
- [ ] 2. Le cards non possiedono tutte la stessa dimensione e il loro contenuto non viene correttamente dimensionato. Sembra che come valore di larghezza venga preso solamente il valore di larghezza del titolo della card.
![photo_2021-09-14_12-04-39](https://user-images.githubusercontent.com/11157241/133238310-8cad9bc7-fff0-4b67-9463-6bdbe4462e4b.jpg)
 - [ ] 3. anche nella pagina feedbacks lato mobile c'è un problema analogo a quello descritto nel punto 1
![Cattura](https://user-images.githubusercontent.com/29338213/133262900-bb7a2655-0bf9-4d66-b25a-b0fd4e30823d.PNG)
 Guarda anche l' altra issue relativa: https://github.com/Weather-Vortex/weather-vortex-client/issues/73

**Comment by silviazandoli** [comment]
https://github.com/fuxingloh/vue-horizontal-list

**Comment by silviazandoli** [comment]
branch: cardsResponsible

**Comment by silviazandoli** [comment]
Nella forecasts lato mobile si vede da sola la card dell'aggregations, poi sotto c'è lo slide delle altre cards
